### ISSUE TITLE
Kafka Consumer batchHandler() not working unless handler

### ISSUE THREAD

**Issue by valeriodurante** [vert-x3/vertx-kafka-client#170] opened 2020-03-24 08:11 UTC
Hi all,
I think this might be a bug, but if it's not maybe it's a wrong report.

### Questions
I try to use the batchHandler, but with no success. Apparently the client connects to kafka server but doesn't want to read messages. 
I searched the problem on the web and I found this solution:
https://groups.google.com/d/topic/vertx/Rz984-m11bU
infact, with both handler and batchHandler all works fine.
Is it correct? In the docs I don't find nothing about it.

### Version

vertx-kafka-client: 3.8.3

### Steps to reproduce

1. Istance KafkaConsumer with handler
2. it works fine
3. change hadler with batchHandler
4. it doesn't work, not poll messages
5. added hadler also
6. it works fine again with batch

### Extra

JVM: 1.8.0_221
auth with kerberos - protocol SASL_TEXT

**Comment by barryzhounb** [comment] 2020-05-13 23:35
Version: compile group: 'io.vertx', name: 'vertx-kafka-client', version: '3.9.0'

Consumer batchHandler()  doesn't work, but Consumer handler() works.

**Comment by barryzhounb** [comment] 2020-06-22 21:08
Hi guys,
Any update?  batchHandler doesn't receive any message from Kafak broker.

```
        KafkaConsumer<Long, byte[]> kafkaConsumer = createConsumer(topicName, props);
        
        kafkaConsumer.batchHandler(batchRecords -> {

            if (batchRecords.size() > 0) {
                for (int i = 0; i < batchRecords.size(); i++) {

                    KafkaConsumerRecord<Long, byte[]> record = batchRecords.recordAt(i);

                    log.info("Consumer received: " + new String(record.value()));
                }
                kafkaConsumer.commit();
            }
        });
```

**Comment by vietj** [comment] 2020-06-24 08:54
can you investigate @ppatierno ?

**Comment by barryzhounb** [comment] 2020-07-14 17:28
Hi @vietj , I saw this issue was put in 3.9.2 milestone, thanks a lot. I am wondering when the fix can be released ? Because we are awaiting its fix. Currently, our project was blocked by it because Kafka consumer does not support batch handler. Or, it there any workaround for batch handler.

**Comment by ppatierno** [comment] 2020-07-15 08:11
@barryzhounb @vietj I have no bandwidth right now to investigate this sorry. If it's a real blocker for you, we are happy to accept a PR with a fix and I will be happy to review. At the end it's open :-)

**Comment by barryzhounb** [comment] 2020-07-16 23:54
Hi @ppatierno and @vietj , I never fix the issue in the vertx, however, you can point out the files that are related to batch handler, I can figure out the issue and try to fix. Thanks.

**Comment by barryzhounb** [comment] 2020-08-14 19:13
Hi @vietj , any updates for this issue?

**Comment by vietj** [comment] 2020-08-18 14:13
it is expected that batchHandler will not trigger reading from Kafka, 

have you tried calling `stream.resume()` instead of setting an handler ?

**Comment by wem** [comment] 2021-11-13 09:01
I think the cause is the KafkaReadStreamImpl hardly depends on the presence of the handler. At least within the schedule method, it calls the run method (where the polling will happen) only if the handler is set. io/vertx/kafka/client/consumer/impl/KafkaReadStreamImpl.java:186

**Comment by calohmn** [comment] 2021-11-13 10:35
@wem I agree (I guess you mean "strongly depends" instead of "hardly")

> it is expected that batchHandler will not trigger reading from Kafka,

I think it should at least be made very clear in the `KafkaConsumer#batchHandler` javadoc that the batchHandler will only be invoked if a handler has been set via the `handler()` method.
In general, I think it would be much more intuitive, if setting the batchHandler alone would also start the polling loop, without the dependence on the `handler()` method.

**Comment by wem** [comment] 2021-11-13 10:44
@calohmn ... Yes for sure i mean strongly, i did update my comment :)

I agree, imo both handlers should be operational independently of each other. 
Another finding is that only the usual handler is covered by tracing. But that's another issue.

**Comment by tsegismont** [comment] 2024-02-05 09:43
Fixed by https://github.com/vert-x3/vertx-kafka-client/pull/261

**Closed by tsegismont** 2024-02-05 09:43 UTC
Labels: bug
